### ISSUE TITLE
Allow DLC installation from app info page (eg. for cartridge copies of games)

### ISSUE THREAD

**Issue by thejsa** [Cruel/freeShop#107]
Apparently you can download DLC from the list of installed titles, however the only game I own that supports DLC is a cartridge copy of Super Smash Bros.

Could you add a button for DLC download on the app info page?

**Comment by Cruel** [comment]
Yeah, I'll add it like I did with demos. But I gotta mostly redo the whole game info screen, so I'll do that in the process. I would've added it already, but without scrolling info there was limited screen space.

**Comment by thejsa** [comment]
If you like, I could draw up some layouts.
I'm hopeless at UI code (unless it's HTML/CSS, which I'm pretty good with) but generally good with UI design.

**Comment by RykenInverse** [comment]
What about for games that don't have a page in FreeShop to begin with? There's quite a few that have their DLC's titlekeys uploaded but not the titlekeys for the software itself.

**Comment by thejsa** [comment]
This should probably be merged with #88 (if possible)

**Comment by Cruel** [comment]
Yeah, I'll just close this issue in favor of that one since title is more specific to what I'll do.

And @RykenInverse I'm not sure it will ever support DLC for titles when it doesn't have the main game title in cache. What will be done is that more titles need to be in cache. When most of them are there, it should be fine. I'm going to rewrite cache script soon to include most eShop games.
