### ISSUE TITLE
[Suggestion] Make it so that I could download 3DS Roms

### ISSUE THREAD

**Issue by rpalmon** [Cruel/freeShop#110]
So instead of making it so that I can download the games for free on the 3ds, can you make a homebrew for this where I could download the roms? That way I wouldn't have to be on CFW?

**Comment by rpalmon** [comment]
and also have a .3dsx version?

**Comment by ihaveamac** [comment]
if you want to use "roms" you need a flash cart. homebrew can't automatically add to it.

about 3dsx: https://gbatemp.net/threads/wip-freeshop-open-source-eshop-clone.426573/

> **Q: Is there a 3dsx version?**
A: No, and with the elevated permissions needed, it's not worth the trouble.

**Comment by rpalmon** [comment]
I do have a 3ds flash cart (sky3ds+) it would be nice to download it to the 3ds sd card and then transfer it over to the flashcart.

**Comment by ihaveamac** [comment]
you'd still need a PC for that. at that point you could just use the PC.

**Comment by rpalmon** [comment]
I know, then can there be a desktop version of freeshop where I could download latest 3ds roms directly from servers and such?

**Comment by Cruel** [comment]
Look at FunKeyCIA which downloads CIAs to your PC just like freeShop downloads them to your 3ds. Then you can convert those CIAs however you like.

**Comment by ihaveamac** [comment]
just a note: converting CIA to ".3ds" doesn't mean Sky3DS will take it.

**Comment by rpalmon** [comment]
Why won't the sky3ds take it?

**Comment by rpalmon** [comment]
also could you link me to FunKeyCIA?

**Comment by ihaveamac** [comment]
it's technically a modified rom, not original. Sky3DS only takes original ones.

**Comment by rpalmon** [comment]
Is a CIA basically like an APK or IPA where you could install it to those perspective phones?

**Comment by cheatfreak47** [comment]
Not really.

The reason it wouldn't work is because the Sky3DS mimic real 3DS carts to work, well enough to fool the 3DS.
The 3DS doesn't accept illegitimate carts.
Even if you could make a Sky3DS pretend it's a modified rom the 3DS would refuse it because the console would see it's unsigned code and refuse it anyway.
The eShop isn't just a repository of 3DS roms, it's special content made to INSTALL to the console. Not roms, and lacks information needed to turn such content into roms.
FunKeyCIA wouldn't work for you either because it's for downloaded eShop content and CIAs and we established you can't just turn CIAs into Sky3DS compatible roms.

Want FreeShop? Get CFW. That's your only option.

**Comment by rpalmon** [comment]
Unfortunately I have FW 11.0 so I can't downgrade to install CFW. Is someone working on a softmod downgrade?

**Comment by ihaveamac** [comment]
maybe, who knows? this is not the right place to discuss this.
