### ISSUE TITLE
Missing Title name / Icon in FBI->Titles for FreeShop (No SMDH magic)

### ISSUE THREAD

**Issue by Favna** [Cruel/freeShop#50]
Title. More than likely an issue of missing SMDH magic on the icon. I'm not sure how exactly you are building FreeShop but [this issue was fixed in the latest bannertool version](https://github.com/Steveice10/bannertool/tree/55f34cfc5444bb23addab606255f3534f3c16cec) as well as [this buildtools](https://github.com/Steveice10/buildtools/commit/9577e0a4e9b2ffa171c939fbf74a68a1f64ecae9) commit (although for buildtools I highly recommend you [use the latest](https://github.com/Steveice10/buildtools/tree/a3770c209b166fc97df193b87d66a65742a3e263))

**Comment by Cruel** [comment]
I have tool auto-builds in another repo here: https://github.com/cpp3ds/3ds-tools/releases

Looks like they're from May 23rd, and I'm assuming the fix you're referring to is here: https://github.com/Steveice10/bannertool/commit/24288b4ec6fc03c91643ab6e86847157296e617b

I'll issue a rebuild and see if it's fixed in next version.

**Comment by Favna** [comment]
Yeah that's one I was essentially referring to but since it was a pull requested merge I generally prefer linking to the merge rather than the other-user's commit ;)

**Comment by Cruel** [comment]
Appears to be fixed in 2.0
