### ISSUE TITLE
[Suggestion] Download CIA as an option

### ISSUE THREAD

**Issue by KelvinHu** [Cruel/freeShop#61]
So I was wondering if it was possible to add an option to freeShop to save the application as a CIA after finishing downloading and installing.

**Comment by Cruel** [comment]
Duplicate of #8 

I don't think this option will be added. I think FunKeyCia is better for that since it makes CIAs much quicker. You'd simply be copy CIAs to SD card before install as opposed to copying them to PC afterward.

I think there is a nice GUI for FunKeyCia too, though you'd have to search for it.
