### ISSUE TITLE
Battery died mid-download, broke home screen controls?

### ISSUE THREAD

**Issue by MyNameIsPAN** [Cruel/freeShop#73]
Hello! I was downloading some games and mid-download, my battery died and shut it off. Once powering it back on, it would boot to the home screen but none of the controls would respond except for powering it off. Booting directly to other programs works fine, but the home screen is stuck for me, any way to fix?

I'm not too understanding of ways I could fix this, but i've tried a couple things:
• Deleted folders in "Nintendo 3DS". This fixed the controls, but removed freeshop, fbi, and other software and entering into something like system settings freezes the console. So I put the files back.
• Deleted freeshop off sd card: nothing changed, the freeshop icon still showed on home screen.

I wonder if deleting the file of the game that broke mid download might help, but i dunno.

Any good way to solve this?

**Comment by I-168** [comment]
try deleting homemenu ext data

**Comment by MyNameIsPAN** [comment]
deleted extdata, removed all the icons except for the default apps, but froze the system if launching any of them or moving over internet browser.

I restored to a previous nand (sysNAND-A9LHAX in Plailect's guide) and it fixed the menu controls and kept FBI in there. However, it still froze the system by trying to launch anything.

**Comment by Cruel** [comment]
freeShop doesn't store any temporary files or anything during download, so there's nothing to delete as far as that goes. It's all handled by the system, and since it was interrupted it's possible it wasn't handled properly.

Either way, I've never heard of this problem happening before. If restoring previous sysnand, along with temporarily removing stuff from SD card, doesn't fix the problem, I don't know what will.
